feat: reduce MemTable to a single layer
ethe/elsm pull request #3
Opened 2024-05-13 10:02 UTC by KKould

issue link: https://github.com/ethe/elsm/issues/2

Tips: I don't know if it's a good idea for the `key` to be `Arc<K>`

2024-05-13 10:47 UTC, KKould commented on src/mem_table.rs
>      pub(crate) fn insert(&mut self, key: Arc<K>, ts: T, value: Option<V>) {
Timestamp types are often basic types such as u64 that can be copied, so they can be cloned/copied to avoid loops. Is it possible to add this type constraint to T for optimization?

2024-05-13 12:34 UTC, ethe requested changes

2024-05-13 12:34 UTC, ethe commented on src/mem_table.rs
> +            .then_with(|| self.ts.cmp(&other.ts))
`(keya, ts_0)` should be larger than `(keya, ts_1)`, because db always needs to get the latest version of key, so larger timestamps should be located earlier in the btree.

2024-05-13 12:34 UTC, ethe commented on src/mem_table.rs
> +            .next_back()
After adjusting the order of `InternalKey`, there is no need to use `next_back` to solve the latest version of a key.

2024-05-14 02:11 UTC, ethe approved these changes

2024-05-14 02:11 UTC, merged